ERFS/ERFS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('booking.urls')),
    path('',include('account.urls')),
    path('',include('restapi.urls')),
    path('admin/', admin.site.urls),
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

ERFS/account/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from  . import views
app_name="account"
urlpatterns = [ 
 path('',views.sucess,name="sucess"),  
 path('userregister/',views.userregister,name="userregister"),
 path('userlogin/',views.userlogin,name="userlogin"),
 path('sucess/',views.sucess,name="sucess"),
 path('userlogout/',views.userlogout,name="userlogout"),
 path('uploadprofile/',views.uploadprofile,name="uploadprofile"),
 path('viewprofile/',views.viewprofile,name="viewprofile"),
]

ERFS/account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin
from django.db.models.signals import post_save
# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    picture = models.ImageField(upload_to="profile/images/")
    bio=models.TextField(max_length=100)
    
def __str__(self):
            return self.user.username

ERFS/account/forms.py
from django import forms
from django.contrib.auth.models import User

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model=User
        fields=('username','first_name','last_name','email','password')

       

       

ERFS/account/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login, authenticate, logout
from django.http import HttpResponse
from .forms import RegistrationForm
from .profile import  profileForm
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from django.contrib import messages
from django.contrib import auth
from django.contrib.auth.models import User
from .models import UserProfile
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    return render(request,template_name="index.html")

def userregister(request):
    if request.method == 'POST':
        formr = RegistrationForm(data=request.POST)
        if formr.is_valid():
            user=formr.save()
            user.set_password(user.password)
            user.save()
            username=formr.cleaned_data.get('username')
            password=formr.cleaned_data.get('password')
            user=authenticate(username=username,password=password)
            login(request,user)
            return redirect('account:sucess')
        else:
            
            return render(request, "main/userregister.html",{'error':"Given Username is Already Taken.Please Try Another."})
            
    else:
        formr = RegistrationForm()
        return render(request, "main/userregister.html", {"formr":formr})


def userlogin(request):
    if request.method=='POST':
        usernam = request.POST['username']
        passwor = request.POST['password']
        user = auth.authenticate(request,username=usernam,password=passwor)
        if user is not None:
            auth.login(request,user)
            return redirect('account:sucess')
            
        else:
            return render(request, "main/userlogin.html",{'error':"Worng Username and Password"})
    else:
        return render(request, "main/userlogin.html")
@login_required
def userlogout(request):
    logout(request)
    return render(request,"main/userlogout.html",{"userlogout":userlogout})

            
def sucess(request):
    return render(request,"main/sucess.html",{"sucess":sucess})
    

@login_required
def uploadprofile(request):
    try:
        if request.method== "POST":
            formp = profileForm(request.POST,request.FILES)
            if formp.is_valid():
                # p = UserProfile.objects.get(user_id=request.user)
                # p.picture=formp.cleaned_data['picture']
                # p.bio=formp.cleaned_data['bio']
                # p.save()
                profile=formp.save(commit=False)
                profile.user=request.user
                profile.save()
                
                return redirect('account:viewprofile')
        else:
            formp = profileForm()
            return render(request, "main/profilecreation.html", {"formp":formp})
    except:
        return render(request, "main/sucess.html",{'error':"Profile is already created"})


@login_required
def viewprofile(request):
    try:
        userp=UserProfile.objects.get(user=request.user.id)
        return render(request, "main/profile.html",{"userp": userp})

    except:
        return render(request, "main/sucess.html",{'error':"Profile is not Created"})



    

ERFS/account/templates/main/book.html
{% extends "main/index.html" %}
{% block content %}
<h1>Login Sucessfull!!!</h1>
{% endblock %}

ERFS/account/templates/main/loginB.html
{% extends "main/index.html" %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h2>Login As Buyer</h2>

    {% if error %}
    <h3>{{error}}</h3>
    {% endif %}

    {{f2.as_p}}
    <button type="submit" class="btn btn-primary">Login</button>
</form>    
  {% endblock %}

ERFS/account/templates/main/profile.html
{% extends "index.html" %}

{% block content %}
<h3 style="text-align: center;">User Profile</h3>
<div style="background-color: wheat; height: 100%;">
    <div style="position: relative; left:810px;">
            <img style="border-radius:50%; margin-top: 20px;" src="{{userp.picture.url}}" height="300" width="300"><br>
            <br>
            <P> <b> Username: {{userp.user.username}} </b></P><br>
            <br>
            <P> <b>Name:{{userp.user.first_name}}    {{userp.user.last_name}}</b></P><br>
             <br>
            <P> <b>Email:{{userp.user.email}}</b></P><br>
            <br>
            <p> <b>Bio:{{userp.bio}}</b></p>
    </div>
</div>         
{% endblock %}

ERFS/account/templates/main/profilecreation.html
{% extends "index.html" %}

{% block content %}

<form action="{% url 'account:uploadprofile' %}" method="POST" enctype="multipart/form-data">
{% csrf_token %}

{% if error %}
    <h5 style="color: red;">{{error}}</h5>
{% endif %}

{{formp.as_p}}

<button type="submit" class="btn btn-success">Upload</button>

</form>
{% endblock %}

ERFS/account/templates/main/register.html
{% extends "main/index.html" %}
{% block content %}
<body>
    <form  method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-success">Register</button>
    </form>
</body>
{% endblock %}

ERFS/account/templates/main/registerB.html
{% extends "main/index.html" %}
{% block content %}
<body>
    <form  method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-success">Register</button>
    </form>
</body>
{% endblock %}

ERFS/account/templates/main/sucess.html
{% extends "index.html" %}
{% block content %}
{% load static %}
<div>
{% if user.is_authenticated %}
<h3 style="margin-left:10px;">Welcome {{request.user.username}} !!!</h3>
{% endif %}
<h2 style="position:relative; left:685px; ">Now You can buy and sell your property</h2>
</div>

<style>
  /* Make the image fully responsive */
  .carousel-inner img {
      width:900 px;
      height: 650px;
      position: relative;
      left:455px;
      right:50px;
  }
</style>

<div id="demo" class="carousel slide" data-ride="carousel">

    <!-- Indicators -->
    <ul class="carousel-indicators">
      <li data-target="#demo" data-slide-to="0" class="active"></li>
      <li data-target="#demo" data-slide-to="1"></li>
      <li data-target="#demo" data-slide-to="2"></li>
    </ul>
  
    <!-- The slideshow -->
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'image/3.jpg' %}" >
      </div>
      <div class="carousel-item">
        <img src="{% static 'image/2.jpg' %}" >
      </div>
      <div class="carousel-item">
        <img src="{% static 'image/1.jpg' %}" >
      </div>
    </div>
  
    <!-- Left and right controls -->
    <a class="carousel-control-prev"  href="#demo" data-slide="prev">
      <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next"  href="#demo" data-slide="next">
      <span class="carousel-control-next-icon"></span>
    </a>
  
  </div>


 {% if user.is_authenticated %}
    {% if error %}
      <h5 style="color: red; text-align: center;">{{error}}</h5>
    {% endif %}
    <div>

       <a style="margin-left:850px; margin-top: 20px;" href="{% url 'account:uploadprofile' %}" class="btn btn-info">Set Profile</a> 
     
       <a style="margin-left:10px; margin-top: 20px;" href="{% url 'account:viewprofile' %}" class="btn btn-info" >View Profile</a>
       

    </div>
 {% endif %}
{% endblock %}

ERFS/account/templates/main/userlogin.html
{% extends "index.html" %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h2 style="text-align: center; margin-top:15px;">User Login</h2>
    {% if error %}
    <h5 style="color: red; text-align: center;">{{error}}</h5>
    {% endif %}
     
    <form id="forml" method="post" action="/main/userlogin/">
      {% csrf_token %}
      <p style="position: relative; left:700px; margin-top:40px;"> Username: <input type="text" name="username" value="" size="50" /></p>
      <br>
      <p style="position: relative; left:700px;">Password: <input type="password" name="password" value="" size="50" /></p>
      <br />

      <input style="position: relative; left:920px;" type="submit" class="btn btn-success" value="submit" />
     </form>  
     
  {% endblock %}

ERFS/account/templates/main/userlogout.html
{% extends "index.html" %}
{% block content %}
<div class="section-inner clearfix">
    <div>
    <h3 style="margin-left:600px; margin-top: 10px;" >You are logged out.Thank You for spending your valueable Time. </h3>
    </div>  

    <div>
    <a style="margin-left:850px; margin-top: 20px;" href="{% url 'account:userlogin' %}" class="btn btn-info"> Login Again</a>
    </div>



</div>
{% endblock %}

ERFS/account/templates/main/userregister.html
{% extends "index.html" %}
{% block content %}
<body>
    <form  method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <h2 style="text-align: center; margin-top:15px;">User Registration</h2>
        {% if error %}
        <h5 style="color: red; text-align: center;">{{error}}</h5>
        {% endif %}
       <table style="position: relative; left:790px;">{{formr.as_table}}</table>

        <p style="text-align: center;"> <a href="{% url 'account:userregister' %}">Click here</a> to Register again.</p>
        

        <button style="position: relative; left:920px;" type="submit" class="btn btn-success">Register</button>
    </form>
</body>
{% endblock %}