ERFS/ERFS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('booking.urls')),
    path('',include('account.urls')),
    path('',include('restapi.urls')),
    path('admin/', admin.site.urls),
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

ERFS/booking/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .import views

app_name = "booking"

urlpatterns=[
   path('assets/booking', views.upload, name="files"),
   path('booking', views.display, name="display"),
    path('booking/delete/<int:pk>/', views.delete_asset, name="delete_asset"),
    path('booking/update/<int:id>/', views.update_asset, name="update_asset" ),
    path('booking/booked/<int:pk>/', views.book_asset, name="book_asset"),
    
 ]

ERFS/booking/models.py
from django.db import models
from django.contrib.auth.models import User

class Asset(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    is_available=models.BooleanField(default=True,null=True)
    asset_Title=models.CharField(max_length=50)
    asset_Type=models.CharField(max_length=20)
    asset_Price=models.IntegerField()
    asset_purpose=models.CharField(max_length=10)
    asset_Location=models.CharField(max_length=50)
    asset_Image=models.FileField(upload_to="assets/",null=True)
    def __str__(self):
        return self.asset_Title
class Booking(models.Model):
    asset=models.OneToOneField(Asset,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    booking_Date=models.DateTimeField(auto_now_add=True)
    booking_Status= models.BooleanField()
    def __str__(self):
        return self.booking_Date

ERFS/booking/forms.py
from django import forms
from .models import Asset

class UploadForm(forms.ModelForm):
    class Meta:
        model = Asset
        fields = ('asset_Title', 'asset_Type', 'asset_Price', 'asset_purpose', 'asset_Location', 'asset_Image')

ERFS/booking/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import Asset,Booking
from account.models import UserProfile
from .forms import UploadForm
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

@login_required(login_url='account:userlogin')
def upload(request):
    #form= UploadForm()
    if request.method == "POST":
        form= UploadForm(request.POST, request.FILES)
        if form.is_valid():
            asset=form.save(commit=False)
            asset.user=request.user
            asset.save()
        return redirect('booking:display') 
    else:      
        form= UploadForm()
        return render(request, "uploads/uploads.html", {"form": form})
@login_required(login_url='account:userlogin')
def update_asset(request, id=None):
    instance= get_object_or_404(Asset, id=id)
    form= UploadForm()
    if request.method == "POST":
        form= UploadForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
        return redirect('booking:display')       
    return render(request, "uploads/upload.html", {"form": form})

def display(request):
    asset= Asset.objects.all()
    return render(request, "uploads/details.html",{"assets": asset})

@login_required(login_url='account:userlogin')
def delete_asset(request, pk= None):
    asset= Asset.objects.get(pk=pk)
    asset.delete()
    return redirect('booking:display')

@login_required(login_url='account:userlogin')

def book_asset(request,pk=None):
    asset = get_object_or_404(Asset, pk=pk)
    if asset.is_available:
        asset.is_available= False
        asset.save()
        b=Booking(user_id=request.user.id)
        b.booking_Date=timezone.now()
        b.asset_id=pk
        b.booking_Status=True
        b.save()
        return redirect('booking:display')

        #messages.info(request, 'You have marked asset {} as booked!'.format(asset.asset_id))
    else:
        asset.is_available = True
        asset.save()
        #messages.info(request, 'You have marked asset {} as available for booking'.format(asset.asset_id) )

    

ERFS/booking/templates/uploads/details.html
 {% extends 'index.html' %}
{% block content %}
<h3 style="text-align: center;">Click to upload your assets.</h3>
<p>
    <a href="{% url 'booking:files' %}" class="btn btn-info" style="position:absolute; left: 600px;">Upload</a>
</p>


  {% if assets %}
        {% for asset in assets %}
        <div>
            <b>Username:</b>{{asset.user.username}}
            <br>
            <b>Title:</b>{{asset.asset_Title}}
            <br>
            <b>Type:</b>{{asset.asset_Type}}
            <br>
            <b>Price:</b>{{asset.asset_Price}}
            <br>
            <b>Purpose:</b>{{asset.asset_purpose}}
            <br>
            <b>Location:</b>{{asset.asset_Location}}
            <br>
            <img src="{{asset.asset_Image.url}}" height="400" width="400">
            <br>
        </div>
            
         

            <div>
                <div><form method="POST" action="{% url 'booking:delete_asset' asset.pk %}">
                {% csrf_token %}
                <button style="position:absolute;left:10px;" type= "submit" class="btn btn-danger">Delete</button>
                 </form>
                 </div>
                <div><form method="GET" action="{% url 'booking:update_asset' asset.pk %}">
                    {% csrf_token %}
                <button style="position:absolute;left:100px;" type="submit" class="btn btn-primary">Update</button></form>
                </div>
            
                {% if asset.is_available %}
               <div><form method="POST" action="{% url 'booking:book_asset' asset.pk %}">
                {% csrf_token %}
                <button style="position:absolute; left:200px;" type="submit" class="btn btn-primary">Book</button></form>
                {% else %}
                <button style="position:absolute;left:200px;" type="submit" class="btn btn-success">Booked</button>
                {% endif %}
                </div>
                <div>
                    <a href="{{asset.asset_Image.url}}" style="position:absolute; left:300px;">Download</a>
                </div>
            </div>
           
             
        {% endfor %}
        </p>
{% else %}

<div class="container">
    <div class="row">
        <div class="card-title">
            <h1>No results</h1>
        </div>
    </div>
</div>

{% endif %}
{% endblock %}

ERFS/booking/templates/uploads/uploads.html
{% extends 'index.html' %}
{% block content %}
<form method = "POST" enctype="multipart/form-data">

    {% csrf_token %}
    {{form.as_p}}

    <button type="submit" class="btn btn-primary btn-sm">Upload</button>

</form>
{% endblock %}